name: Test

on: push


jobs:
  information:
    runs-on: ubuntu-latest
    steps:
      - name: saludos desde git actions
        run: echo "hola desde la shell de github actions"

      - name: info del runner
        run: |
          echo "tipo de runner: $RUNNER_OS"
          echo "tipo de python3: $(python3 --version)"
          echo "tipo de git: $(git --version)"
