name: main-test

on: push

jobs:
  my-test:
    runs-on: ubuntu-latest
    steps:
        - name: saludo desde github actions
          run: echo "bienvenido este es mi test"

        - name: info del runner
          run: | 
            echo "runner: $RUNNER_OS"
            echo "git: $(git --version)"
            echo "python3: $(python3 --version)"
            echo "fecha: $(date)"

            
