name: test

on: 
  push:
    branches:
      - main 

jobs:
  multiple_os:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-slim]        
        node-v: [18,19]

    runs-on: ${{ matrix.os }}    
    steps:
      - name: ejecutando msj desde varios ubuntu
        run: echo "hola desde ubuntu"

      - name: descargando nodejs  
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-v }}


  multiple_python:
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    runs-on: ubuntu-slim
    steps:
      - name: descargar multiples python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}   

